parameters:
#    cv_front.example.class: Cv\FrontBundle\Example

services:
#    cv_front.example:
#        class: %cv_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
